package de.rytrox.spicy.sql;

import org.jetbrains.annotations.NotNull;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;

record StatementWrapper(String query, Object... args) {

    /**
     * Builds the prepared Statement based on this wrapper
     *
     * @param connection the connection to the database. Cannot be null
     *
     * @return the prepared statement
     * @throws SQLException if a sql related error occurs
     */
    public PreparedStatement build(@NotNull Connection connection) throws SQLException {
        //Do not close this Statement here!!
        PreparedStatement ps = connection.prepareStatement(query);
        if(args != null)
            for(int i = 0; i < args.length; i++) ps.setString(i + 1, args[i].toString());
        return ps;
    }

    /**
     * Builds the prepared Statement based on this wrapper
     *
     * @param connection the connection to the database. Cannot be null
     * @param autoGeneratedKeys the param of returning auto generated keys
     *
     * @return the prepared statement
     * @throws SQLException if a sql related error occurs
     */
    public PreparedStatement build(@NotNull Connection connection, int autoGeneratedKeys) throws SQLException {
        //Do not close this Statement here!!
        PreparedStatement ps = connection.prepareStatement(query, autoGeneratedKeys);
        if(args != null)
            for(int i = 0; i < args.length; i++) ps.setString(i + 1, args[i].toString());
        return ps;
    }
}
